# Generated by Django 3.1.2 on 2020-10-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
